### ISSUE TITLE
Namespace Confusion

### ISSUE THREAD

**Issue by russellpierce** [masspastore/overlapping#11]
I added several comments within code context as part of a blame.  In short, you've a line that reads `attachNamespace("ggplot")`.  For reasons I describe there nobody will ever actually reach this line of code, but if they did it would produce an error because the name of the namespace you want is `ggplot2` rather than `ggplot`.  I also included recommendations to demote ggplot from an `include` to `includeFrom` and some comments about the degree to which the whole 'requireNamespace' dance is really needed in the first place - perhaps this is a left over from before you packaged this function?

**Comment by masspastore** [comment]
Thanks @russellpierce you are right. 
I deleted all these commands because `ggplot2` is directly imported in the `NAMESPACE`.
