### ISSUE TITLE
Consider Adding Statement of Need to README.md

### ISSUE THREAD

**Issue by russellpierce** [masspastore/overlapping#3]

**Comment by soodoku** [comment]
@masspastore: treat it as what problem are you trying to solve. You have some material in the paper. Readme is the landing page on github --- use it to tell people succinctly what your package does and how.

**Comment by masspastore** [comment]
Thanks @soodoku for the suggestions, I updated the README.md file.

**Comment by soodoku** [comment]
Feel free to close this issue.
