### ISSUE TITLE
Consider adding community guidelines to README.md

### ISSUE THREAD

**Issue by russellpierce** [masspastore/overlapping#5]
In addition, if you intend to offer support/issues via Github, you can add that link to your DESCRIPTION file via the BugReports field: https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file.

**Comment by russellpierce** [comment]
I'm just working through the checklist. :) As the other reviewer said GitHub is where some people finding your package will land. If you just want to add "users may contact the author at email@addy.com for support or to report issues" to the README, that would be enough.

**Comment by masspastore** [comment]
Thanks @russellpierce for the suggestions, I updated the README.md file.

**Comment by soodoku** [comment]
Feel free to close this issue @masspastore
